In [1]:
# import lib
import pandas as pd
import numpy as np
import itertools
import pandas as pd
import numpy as np
import itertools
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import PassiveAggressiveClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn import metrics
import matplotlib.pyplot as plt

In [2]:
# load the data
dataset = pd.read_csv('news.csv',index_col = None)

In [3]:
dataset

Unnamed: 0                                              title  \
0           8476                       You Can Smell Hillary’s Fear   
1          10294  Watch The Exact Moment Paul Ryan Committed Pol...   
2           3608        Kerry to go to Paris in gesture of sympathy   
3          10142  Bernie supporters on Twitter erupt in anger ag...   
4            875   The Battle of New York: Why This Primary Matters   
...          ...                                                ...   
6330        4490  State Department says it can't find emails fro...   
6331        8062  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332        8622  Anti-Trump Protesters Are Tools of the Oligarc...   
6333        4021  In Ethiopia, Obama seeks progress on peace, se...   
6334        4330  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 4 columns]

In [4]:
df = dataset

In [5]:
df.columns

Index(['Unnamed: 0', 'title', 'text', 'label'], dtype='object')

In [6]:
# drop the unwanted column
df.drop('Unnamed: 0',axis =1)

title  \
0                          You Can Smell Hillary’s Fear   
1     Watch The Exact Moment Paul Ryan Committed Pol...   
2           Kerry to go to Paris in gesture of sympathy   
3     Bernie supporters on Twitter erupt in anger ag...   
4      The Battle of New York: Why This Primary Matters   
...                                                 ...   
6330  State Department says it can't find emails fro...   
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...   
6332  Anti-Trump Protesters Are Tools of the Oligarc...   
6333  In Ethiopia, Obama seeks progress on peace, se...   
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...   

                                                   text label  
0     Daniel Greenfield, a Shillman Journalism Fello...  FAKE  
1     Google Pinterest Digg Linkedin Reddit Stumbleu...  FAKE  
2     U.S. Secretary of State John F. Kerry said Mon...  REAL  
3     — Kaydee King (@KaydeeKing) November 9, 2016 T...  FAKE  
4     It's primary day in New York and front-runners...  REAL  
...                                                 ...   ...  
6330  The State Department told the Republican Natio...  REAL  
6331  The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...  FAKE  
6332   Anti-Trump Protesters Are Tools of the Oligar...  FAKE  
6333  ADDIS ABABA, Ethiopia —President Obama convene...  REAL  
6334  Jeb Bush Is Suddenly Attacking Trump. Here's W...  REAL  

[6335 rows x 3 columns]

In [7]:
# x is input and y is output
x = df['title']
y = df['label']

In [8]:
#spliting data into training and testing
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.33,random_state =53)

# Count Vector

In [9]:
# countvector 
count_vect = CountVectorizer(stop_words ='english') # stop words = engkish will remove the words is the all a like that words
count_train = count_vect.fit_transform(x_train) 
print(count_train)
count_test = count_vect.transform(x_test)

  (0, 5763)	1
  (0, 5842)	1
  (0, 2475)	1
  (0, 5161)	1
  (0, 1560)	1
  (0, 1011)	1
  (0, 7360)	1
  (0, 2394)	1
  (0, 397)	1
  (0, 4616)	1
  (0, 7373)	1
  (1, 7360)	1
  (1, 7163)	1
  (1, 2237)	1
  (1, 6236)	1
  (1, 4947)	1
  (2, 801)	1
  (2, 1128)	1
  (2, 2453)	1
  (3, 6196)	1
  (3, 4157)	1
  (3, 4785)	1
  (3, 4251)	1
  (3, 3035)	1
  (3, 4027)	1
  :	:
  (4240, 3403)	1
  (4240, 1961)	1
  (4240, 4889)	1
  (4240, 5963)	1
  (4241, 2358)	1
  (4241, 61)	1
  (4241, 5779)	1
  (4241, 943)	1
  (4242, 7360)	1
  (4242, 1424)	1
  (4242, 5133)	1
  (4242, 7816)	1
  (4242, 7702)	1
  (4242, 4464)	1
  (4242, 4013)	1
  (4242, 3981)	1
  (4242, 204)	1
  (4242, 5915)	1
  (4243, 7360)	1
  (4243, 1140)	1
  (4243, 1818)	1
  (4243, 6159)	1
  (4243, 6141)	1
  (4243, 4419)	1
  (4243, 6823)	1


In [10]:
# to get the length of vec
len(count_vect.get_feature_names_out())

7959

In [11]:
# know hw the input transform
print(count_train.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [12]:
# to know how the output transform
y_train

2576    FAKE
1539    FAKE
5163    REAL
2615    FAKE
4270    FAKE
        ... 
662     REAL
3261    REAL
5883    REAL
2933    REAL
797     REAL
Name: label, Length: 4244, dtype: object

In [13]:
# to create a model
classifier = MultinomialNB()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
print("accuracy: %0.3f" %score)

accuracy: 0.797


In [14]:
from sklearn.metrics import confusion_matrix
cm = metrics.confusion_matrix(y_test,pred,labels =['FAKE','REAL'])

In [15]:
cm

array([[773, 235],
       [189, 894]], dtype=int64)

In [16]:
from sklearn.metrics import classification_report
report = classification_report(y_test,pred)

In [17]:
print(report)

              precision    recall  f1-score   support

        FAKE       0.80      0.77      0.78      1008
        REAL       0.79      0.83      0.81      1083

    accuracy                           0.80      2091
   macro avg       0.80      0.80      0.80      2091
weighted avg       0.80      0.80      0.80      2091



In [18]:
df['title'][0]

'You Can Smell Hillary’s Fear'

In [19]:
count_train[[0]]

<1x7959 sparse matrix of type '<class 'numpy.int64'>'
	with 11 stored elements in Compressed Sparse Row format>

In [20]:
x_train[0]

'You Can Smell Hillary’s Fear'

In [21]:
classifier.predict(count_train[[0]])

array(['FAKE'], dtype='<U4')

In [22]:
results = []

In [23]:
# PassiveAggressiveClassifier
classifier = PassiveAggressiveClassifier()
classifier.fit(count_train, y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
results.append(('PassiveAggressive', score))
print("PassiveAggressive accuracy: %0.3f" % score)

PassiveAggressive accuracy: 0.765


In [24]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('RandomForestClassifier',score))
print("accuracy: %0.3f" %score)

accuracy: 0.808


In [25]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('DecisionTreeClassifier',score))
print("accuracy: %0.3f" %score)

accuracy: 0.764


In [26]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('LogisticRegression',score))
print("accuracy: %0.3f" %score)

accuracy: 0.807


In [27]:
from sklearn.svm import SVC
classifier = SVC()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('SVC',score))

print("accuracy: %0.3f" %score)

accuracy: 0.804


In [28]:
# Create DataFrame
algorithm_comp = pd.DataFrame(results, columns=['Algorithm', 'Accuracy'])

print(algorithm_comp)


                Algorithm  Accuracy
0       PassiveAggressive  0.764706
1  RandomForestClassifier  0.807747
2  DecisionTreeClassifier  0.763749
3      LogisticRegression  0.806791
4                     SVC  0.804400


In [30]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
from sklearn.metrics import classification_report
report = classification_report(y_test,pred)
print(report)

              precision    recall  f1-score   support

        FAKE       0.77      0.83      0.80      1008
        REAL       0.83      0.77      0.80      1083

    accuracy                           0.80      2091
   macro avg       0.80      0.80      0.80      2091
weighted avg       0.80      0.80      0.80      2091



In [42]:
classifier.predict(count_train[661])

array(['REAL'], dtype=object)

# TF IDF Vector

In [31]:
tfid_vect = TfidfVectorizer(stop_words ='english')
count_train = tfid_vect.fit_transform(x_train)
print(count_train)
count_test = count_vect.transform(x_test)

  (0, 5763)	0.346605480233628
  (0, 5842)	0.3767601806099568
  (0, 2475)	0.3767601806099568
  (0, 5161)	0.346605480233628
  (0, 1560)	0.3767601806099568
  (0, 1011)	0.29532923002507444
  (0, 7360)	0.12129935283439379
  (0, 2394)	0.18922301728552432
  (0, 397)	0.20125442786171469
  (0, 4616)	0.2921052340852979
  (0, 7373)	0.2651745296487456
  (1, 7360)	0.18342706282928595
  (1, 7163)	0.40357312802285594
  (1, 2237)	0.5241316108799687
  (1, 6236)	0.5697310967080482
  (1, 4947)	0.45185813579029693
  (2, 801)	0.4632921828956465
  (2, 1128)	0.564372529874744
  (2, 2453)	0.683259834024047
  (3, 6196)	0.31940545290593947
  (3, 4157)	0.37342295226891226
  (3, 4785)	0.37342295226891226
  (3, 4251)	0.37342295226891226
  (3, 3035)	0.37342295226891226
  (3, 4027)	0.37342295226891226
  :	:
  (4240, 3403)	0.3749477704238797
  (4240, 1961)	0.37969761277453634
  (4240, 4889)	0.422738514913017
  (4240, 5963)	0.45062384744664014
  (4241, 2358)	0.45345243237434196
  (4241, 61)	0.4621568896880738
  (4241,

In [33]:
len(tfid_vect.get_feature_names_out())

7959

In [34]:
print(count_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [59]:
count_test.shape

(2091, 7959)

In [37]:
results = []

# PassiveAggressiveClassifier
classifier = PassiveAggressiveClassifier()
classifier.fit(count_train, y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
results.append(('PassiveAggressive', score))
# print("PassiveAggressive accuracy: %0.3f" % score)

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('RandomForestClassifier',score))
# print("accuracy: %0.3f" %score)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('DecisionTreeClassifier',score))
# print("accuracy: %0.3f" %score)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('LogisticRegression',score))
# print("accuracy: %0.3f" %score)

from sklearn.svm import SVC
classifier = SVC()
classifier.fit(count_train,y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test,pred)
results.append(('SVC',score))
# print("accuracy: %0.3f" %score)

# Create DataFrame
algorithm_comp = pd.DataFrame(results, columns=['Algorithm', 'Accuracy'])

print(algorithm_comp)


                Algorithm  Accuracy
0       PassiveAggressive  0.763271
1  RandomForestClassifier  0.787661
2  DecisionTreeClassifier  0.728838
3      LogisticRegression  0.807269
4                     SVC  0.809182


In [45]:
# Find the algorithm with the highest accuracy
best_algorithm = max(results, key=lambda x: x[1])
best_algorithm_name = best_algorithm[0]

# Re-train the best classifier and generate the classification report
if best_algorithm_name == 'PassiveAggressive':
    best_classifier = PassiveAggressiveClassifier()
elif best_algorithm_name == 'RandomForestClassifier':
    best_classifier = RandomForestClassifier()
elif best_algorithm_name == 'DecisionTreeClassifier':
    best_classifier = DecisionTreeClassifier()
elif best_algorithm_name == 'LogisticRegression':
    best_classifier = LogisticRegression()
elif best_algorithm_name == 'SVC':
    best_classifier = SVC()

best_classifier.fit(count_train, y_train)
pred = best_classifier.predict(count_test)
report = metrics.classification_report(y_test, pred)
print(f"Classification Report for {best_algorithm_name}:\n{report}")

Classification Report for SVC:
              precision    recall  f1-score   support

        FAKE       0.77      0.86      0.81      1008
        REAL       0.86      0.76      0.80      1083

    accuracy                           0.81      2091
   macro avg       0.81      0.81      0.81      2091
weighted avg       0.81      0.81      0.81      2091



In [48]:
classifier.predict(count_train[661])

array(['REAL'], dtype=object)

# Hashing vector

In [51]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size =0.33,random_state =53)

In [54]:
len(count_vect.get_feature_names_out())

7959

In [52]:
hash_vect = HashingVectorizer(stop_words ='english')
count_train = hash_vect.fit_transform(x_train)
print(count_train)
count_test = count_vect.transform(x_test)

  (0, 92453)	-0.30151134457776363
  (0, 119590)	0.30151134457776363
  (0, 152399)	0.30151134457776363
  (0, 277491)	-0.30151134457776363
  (0, 366521)	-0.30151134457776363
  (0, 757755)	0.30151134457776363
  (0, 791091)	0.30151134457776363
  (0, 907820)	0.30151134457776363
  (0, 963796)	0.30151134457776363
  (0, 971307)	0.30151134457776363
  (0, 1007753)	0.30151134457776363
  (1, 46353)	0.4472135954999579
  (1, 413315)	-0.4472135954999579
  (1, 421751)	-0.4472135954999579
  (1, 506429)	-0.4472135954999579
  (1, 907820)	0.4472135954999579
  (2, 222621)	-0.5773502691896258
  (2, 755395)	0.5773502691896258
  (2, 835051)	0.5773502691896258
  (3, 22218)	0.35355339059327373
  (3, 162168)	-0.35355339059327373
  (3, 256235)	0.35355339059327373
  (3, 556547)	-0.35355339059327373
  (3, 735306)	-0.35355339059327373
  (3, 897876)	0.35355339059327373
  :	:
  (4240, 239032)	-0.3779644730092272
  (4240, 678349)	0.3779644730092272
  (4240, 901028)	0.3779644730092272
  (4240, 907820)	0.3779644730092272

In [55]:
print(count_train.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [60]:
count_test.shape

(2091, 7959)

In [62]:
# Initialize HashingVectorizer
hash_vect = HashingVectorizer(stop_words='english')

# Transform train and test data
count_train = hash_vect.fit_transform(x_train)
count_test = hash_vect.transform(x_test)



In [63]:
# List to store results
results = []

# PassiveAggressiveClassifier
classifier = PassiveAggressiveClassifier()
classifier.fit(count_train, y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
results.append(('PassiveAggressive', score))

# RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(count_train, y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
results.append(('RandomForestClassifier', score))

# DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(count_train, y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
results.append(('DecisionTreeClassifier', score))

# LogisticRegression
classifier = LogisticRegression()
classifier.fit(count_train, y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
results.append(('LogisticRegression', score))

# SVC
classifier = SVC()
classifier.fit(count_train, y_train)
pred = classifier.predict(count_test)
score = metrics.accuracy_score(y_test, pred)
results.append(('SVC', score))


In [64]:

# Create DataFrame
algorithm_comp = pd.DataFrame(results, columns=['Algorithm', 'Accuracy'])
print(algorithm_comp)

# Find the algorithm with the highest accuracy
best_algorithm = max(results, key=lambda x: x[1])
best_algorithm_name = best_algorithm[0]

# Re-train the best classifier and generate the classification report
if best_algorithm_name == 'PassiveAggressive':
    best_classifier = PassiveAggressiveClassifier()
elif best_algorithm_name == 'RandomForestClassifier':
    best_classifier = RandomForestClassifier()
elif best_algorithm_name == 'DecisionTreeClassifier':
    best_classifier = DecisionTreeClassifier()
elif best_algorithm_name == 'LogisticRegression':
    best_classifier = LogisticRegression()
elif best_algorithm_name == 'SVC':
    best_classifier = SVC()

best_classifier.fit(count_train, y_train)
pred = best_classifier.predict(count_test)
report = metrics.classification_report(y_test, pred)
print(f"Classification Report for {best_algorithm_name}:\n{report}")


                Algorithm  Accuracy
0       PassiveAggressive  0.764706
1  RandomForestClassifier  0.815878
2  DecisionTreeClassifier  0.757054
3      LogisticRegression  0.800096
4                     SVC  0.806313
Classification Report for RandomForestClassifier:
              precision    recall  f1-score   support

        FAKE       0.76      0.88      0.82      1008
        REAL       0.87      0.74      0.80      1083

    accuracy                           0.81      2091
   macro avg       0.81      0.81      0.81      2091
weighted avg       0.82      0.81      0.81      2091

